# Generated by Django 3.0.3 on 2020-10-17 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Code', models.IntegerField(unique=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Class', models.CharField(choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=2)),
                ('Village', models.CharField(max_length=100)),
                ('Geog', models.CharField(max_length=100)),
                ('Dzongkhag', models.CharField(max_length=100)),
                ('Present_Adress', models.CharField(max_length=200)),
                ('Name_of_Father', models.IntegerField(unique=True)),
                ('Contact_No1', models.CharField(max_length=100)),
                ('Name_of_Mother', models.CharField(max_length=100)),
                ('Contact_No2', models.CharField(max_length=100)),
                ('Infomation_Entered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('Profile_photo', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
    ]
