# Generated by Django 3.0.3 on 2020-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Contact_No1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Contact_No2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Middle_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Name_of_Father',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Student_Code',
            field=models.DecimalField(decimal_places=3, max_digits=14, unique=True),
        ),
    ]
