# Generated by Django 3.0.3 on 2020-10-19 05:25

from django.db import migrations, models
import studentinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_auto_20201019_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Confirm_Student_Code',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Student_Code',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
