# Generated by Django 3.0.3 on 2020-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0003_auto_20201019_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Profile_photo',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='profile_pics', width_field='picture_widht'),
        ),
    ]
