# Generated by Django 3.0.3 on 2020-10-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0004_auto_20201020_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Blood_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Profile_photo',
            field=models.ImageField(blank=True, max_length=264, null=True, upload_to=''),
        ),
    ]
