# Generated by Django 3.0.3 on 2020-10-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0006_studentdetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='Confirm_Student_Code',
        ),
    ]
